image: Ubuntu1804
stack: node 14
branches:
  only:
    - main
cache: node_modules
install:
  - npm install
build: off

build_script:
  -npm run build 

test_script:
  - npm run lint

deploy_script:  
  - git config --global credential.helper store
  - git config --global user.name edelsid
  - git config --global user.email eradonna@yandex.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose